export const mockPetData = [
  {
    id: '1',
    name: 'Bella',
    type: 'Dog',
    breed: 'Labrador Retriever',
    owner: 'John Doe',
    ownerEmail: 'johndoe@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '2',
    name: 'Luna',
    type: 'Cat',
    breed: 'Siamese',
    owner: 'Jane Smith',
    ownerEmail: 'janesmith@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '3',
    name: 'Charlie',
    type: 'Dog',
    breed: 'Golden Retriever',
    owner: 'Michael Johnson',
    ownerEmail: 'michaeljohnson@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '4',
    name: 'Lucy',
    type: 'Cat',
    breed: 'Persian',
    owner: 'Emily Davis',
    ownerEmail: 'emilydavis@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '5',
    name: 'Max',
    type: 'Dog',
    breed: 'Bulldog',
    owner: 'William Brown',
    ownerEmail: 'williambrown@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '6',
    name: 'Daisy',
    type: 'Cat',
    breed: 'Maine Coon',
    owner: 'Olivia Wilson',
    ownerEmail: 'oliviawilson@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '7',
    name: 'Buddy',
    type: 'Dog',
    breed: 'Beagle',
    owner: 'James Taylor',
    ownerEmail: 'jamestaylor@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '8',
    name: 'Lola',
    type: 'Cat',
    breed: 'Bengal',
    owner: 'Sophia Moore',
    ownerEmail: 'sophiamoore@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '9',
    name: 'Rocky',
    type: 'Dog',
    breed: 'Poodle',
    owner: 'Benjamin Anderson',
    ownerEmail: 'benjaminanderson@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '10',
    name: 'Molly',
    type: 'Cat',
    breed: 'Ragdoll',
    owner: 'Ava Thomas',
    ownerEmail: 'avathomas@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '11',
    name: 'Jake',
    type: 'Dog',
    breed: 'Boxer',
    owner: 'Henry Jackson',
    ownerEmail: 'henryjackson@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '12',
    name: 'Zoe',
    type: 'Cat',
    breed: 'Sphynx',
    owner: 'Mia White',
    ownerEmail: 'miawhite@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '13',
    name: 'Toby',
    type: 'Dog',
    breed: 'Dachshund',
    owner: 'Alexander Harris',
    ownerEmail: 'alexanderharris@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '14',
    name: 'Misty',
    type: 'Cat',
    breed: 'British Shorthair',
    owner: 'Isabella Martin',
    ownerEmail: 'isabellamartin@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '15',
    name: 'Buster',
    type: 'Dog',
    breed: 'Siberian Husky',
    owner: 'Daniel Thompson',
    ownerEmail: 'danielthompson@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '16',
    name: 'Nala',
    type: 'Cat',
    breed: 'Abyssinian',
    owner: 'Charlotte Garcia',
    ownerEmail: 'charlottegarcia@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '17',
    name: 'Oscar',
    type: 'Dog',
    breed: 'Shih Tzu',
    owner: 'Lucas Martinez',
    ownerEmail: 'lucasmartinez@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '18',
    name: 'Simba',
    type: 'Cat',
    breed: 'Scottish Fold',
    owner: 'Amelia Rodriguez',
    ownerEmail: 'ameliarodriguez@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '19',
    name: 'Jack',
    type: 'Dog',
    breed: 'Border Collie',
    owner: 'Matthew Lee',
    ownerEmail: 'matthewlee@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '20',
    name: 'Shadow',
    type: 'Cat',
    breed: 'Russian Blue',
    owner: 'Harper Perez',
    ownerEmail: 'harperperez@gmail.com',
    createdAt: new Date(),
  },
];
