export const mockData = [
  {
    id: '1',
    name: 'John Doe',
    username: 'john.doe',
    email: 'johndoe@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '2',
    name: 'Jane Smith',
    username: 'jane.smith',
    email: 'janesmith@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '3',
    name: 'Michael Johnson',
    username: 'michael.johnson',
    email: 'michaeljohnson@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '4',
    name: 'Emily Davis',
    username: 'emily.davis',
    email: 'emilydavis@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '5',
    name: 'William Brown',
    username: 'william.brown',
    email: 'williambrown@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '6',
    name: 'Olivia Wilson',
    username: 'olivia.wilson',
    email: 'oliviawilson@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '7',
    name: 'James Taylor',
    username: 'james.taylor',
    email: 'jamestaylor@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '8',
    name: 'Sophia Moore',
    username: 'sophia.moore',
    email: 'sophiamoore@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '9',
    name: 'Benjamin Anderson',
    username: 'benjamin.anderson',
    email: 'benjaminanderson@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '10',
    name: 'Ava Thomas',
    username: 'ava.thomas',
    email: 'avathomas@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '11',
    name: 'Henry Jackson',
    username: 'henry.jackson',
    email: 'henryjackson@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '12',
    name: 'Mia White',
    username: 'mia.white',
    email: 'miawhite@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '13',
    name: 'Alexander Harris',
    username: 'alexander.harris',
    email: 'alexanderharris@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '14',
    name: 'Isabella Martin',
    username: 'isabella.martin',
    email: 'isabellamartin@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '15',
    name: 'Daniel Thompson',
    username: 'daniel.thompson',
    email: 'danielthompson@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '16',
    name: 'Charlotte Garcia',
    username: 'charlotte.garcia',
    email: 'charlottegarcia@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '17',
    name: 'Lucas Martinez',
    username: 'lucas.martinez',
    email: 'lucasmartinez@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '18',
    name: 'Amelia Rodriguez',
    username: 'amelia.rodriguez',
    email: 'ameliarodriguez@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '19',
    name: 'Matthew Lee',
    username: 'matthew.lee',
    email: 'matthewlee@gmail.com',
    createdAt: new Date(),
  },
  {
    id: '20',
    name: 'Harper Perez',
    username: 'harper.perez',
    email: 'harperperez@gmail.com',
    createdAt: new Date(),
  },
];
